### ISSUE TITLE
Unable to install package pybmr>=0.7.2

### ISSUE THREAD

**Issue by Dehumanizer77** [slesinger/HomeAssistant-BMR#7]
I am opening a new issue for this, as the issue with pybmr not beeing installed automatically after HA core upgrade still persists, as I have mentioned here: https://github.com/slesinger/HomeAssistant-BMR/issues/6#issuecomment-1591436218

Every time I upgrade Home Assistant, I have to go inside the HA docker container and execute "pip install pybmr" and restart HA once again. 
Until I do this, pybmr is not installed and this error message appears in logs:
```
Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 11:39:57 (3 occurrences)
Last logged: 11:40:25

Unable to install package pybmr>=0.7.2: ERROR: Cannot install pybmr==0.7.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
```
The installation with pip install pybmr ends successfuly, however with some warnings, this is a full output:
```
Collecting pybmr
  Downloading pybmr-0.7.2-py3-none-any.whl (13 kB)
Collecting cachetools==4.2.4 (from pybmr)
  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting certifi==2021.10.8 (from pybmr)
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 kB 4.3 MB/s eta 0:00:00
Collecting charset-normalizer==2.0.9 (from pybmr)
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting idna==3.3 (from pybmr)
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 7.0 MB/s eta 0:00:00
Collecting requests==2.28.0 (from pybmr)
  Downloading requests-2.28.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 7.8 MB/s eta 0:00:00
Collecting requests-toolbelt==0.9.1 (from pybmr)
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.3/54.3 kB 5.4 MB/s eta 0:00:00
Collecting urllib3==1.26.14 (from pybmr)
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 15.4 MB/s eta 0:00:00
WARNING: Skipping /usr/local/lib/python3.11/site-packages/croniter-1.0.6.dist-info due to invalid metadata entry 'name'
Installing collected packages: certifi, urllib3, idna, charset-normalizer, cachetools, requests, requests-toolbelt, pybmr
  Attempting uninstall: certifi
    Found existing installation: certifi 2023.7.22
    Uninstalling certifi-2023.7.22:
      Successfully uninstalled certifi-2023.7.22
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.16
    Uninstalling urllib3-1.26.16:
      Successfully uninstalled urllib3-1.26.16
  Attempting uninstall: idna
    Found existing installation: idna 3.4
    Uninstalling idna-3.4:
      Successfully uninstalled idna-3.4
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.2.0
    Uninstalling charset-normalizer-3.2.0:
      Successfully uninstalled charset-normalizer-3.2.0
  Attempting uninstall: cachetools
    Found existing installation: cachetools 5.3.1
    Uninstalling cachetools-5.3.1:
      Successfully uninstalled cachetools-5.3.1
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: requests-toolbelt
    Found existing installation: requests-toolbelt 1.0.0
    Uninstalling requests-toolbelt-1.0.0:
      Successfully uninstalled requests-toolbelt-1.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
homeassistant 2023.9.3 requires requests==2.31.0, but you have requests 2.28.0 which is incompatible.
aiorecollect 2023.9.0 requires certifi>=2023.07.22, but you have certifi 2021.10.8 which is incompatible.
zwave-me-ws 0.4.3 requires requests<3.0.0,>=2.28.1, but you have requests 2.28.0 which is incompatible.
simplisafe-python 2023.8.0 requires certifi>=2023.07.22, but you have certifi 2021.10.8 which is incompatible.
nuheat 1.0.1 requires requests>=2.28.1, but you have requests 2.28.0 which is incompatible.
pyisy 3.1.14 requires requests>=2.28.1, but you have requests 2.28.0 which is incompatible.
locationsharinglib 5.0.1 requires cachetools>=5.3.0, but you have cachetools 4.2.4 which is incompatible.
locationsharinglib 5.0.1 requires requests>=2.28.2, but you have requests 2.28.0 which is incompatible.
pyswitchbot 0.39.1 requires requests>=2.28.1, but you have requests 2.28.0 which is incompatible.
pyairvisual 2023.8.1 requires certifi>=2023.07.22, but you have certifi 2021.10.8 which is incompatible.
Successfully installed cachetools-4.2.4 certifi-2021.10.8 charset-normalizer-2.0.9 idna-3.3 pybmr-0.7.2 requests-2.28.0 requests-toolbelt-0.9.1 urllib3-1.26.14
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

```
After intallation of pybmr, everything works fine.

I am running HA in Virtualbox if that matters. 

Is there any way how to fix it? It's quite annoying having to install pybmr manually after every upgrade...

Thanks.

**Comment by slesinger** [comment]
I have updated dependencies in pybmr. I hope this helps.

**Comment by Dehumanizer77** [comment]
Well, it apparently did not.
After HA update, I am getting this error:
Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 15:57:23 (3 occurrences)
Last logged: 15:57:54

Unable to install package pybmr>=0.7.4: ERROR: Cannot install pybmr==0.7.4, pybmr==0.7.7 and pybmr==0.7.8 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

When I then install pybmr manually, it works.
The error message suggests that for some reason it wants to install multiple versions of pybmr?

**Comment by Rotif** [comment]
"When I then install pybmr manually, it works. The error message suggests that for some reason it wants to install multiple versions of pybmr?"

@Dehumanizer77 
I'm still getting the message like you: Unable to install package pybmr>=0.7.4: ERROR: Cannot install pybmr==0.7.4, pybmr==0.7.7 and pybmr==0.7.8
Pease, is there a guide somewhere on how to manually install pybmr?
Thanks

**Comment by Dehumanizer77** [comment]
@Rotif 
From the terminal in HA or from ssh connection:
`docker exec -it homeassistant pip install --no-deps pybmr==0.7.8`

**Comment by Dehumanizer77** [comment]
Yes, exactly.

**Comment by Rotif** [comment]
I will rather try HC64 communications via modbus over ethernet TCP.

**Comment by Dehumanizer77** [comment]
@Rotif I was trying that, I somehow wasn't successful (although I did not spend much time on that actually), I'd be glad to know if you had some success with that. 
However apart from this hassle, the bmr integration works OK (still there are some things that I would change/add, but it doesn't seem that it's actively developed anymore)

**Comment by Rotif** [comment]
Do you have shutters too?

**Comment by Dehumanizer77** [comment]
Yes I do.

**Comment by zelial** [comment]
Same issue, apparently pybmr and HA (2024.2.5 container) can't agree on the version of the `charset-normalizer` package:

Un-quieted log of what HACS tries to do:
```
/usr/local/bin/python3 -m 'pip' 'install' 'pybmr>=0.7.8' '--timeout' '60' '--upgrade' '--constraint' '/usr/src/homeassistant/homeassistant/package_constraints.txt' '--user'
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting pybmr>=0.7.8
  Downloading pybmr-0.7.8.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Collecting cachetools==4.2.4 (from pybmr>=0.7.8)
  Downloading cachetools-4.2.4-py3-none-any.whl.metadata (4.8 kB)
Collecting certifi==2023.11.17 (from pybmr>=0.7.8)
  Downloading https://wheels.home-assistant.io/musllinux-index/certifi-2023.11.17-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 3.2 MB/s eta 0:00:00
Collecting chardet==3.0.4 (from pybmr>=0.7.8)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: idna==3.6 in /usr/local/lib/python3.12/site-packages (from pybmr>=0.7.8) (3.6)
Requirement already satisfied: requests-toolbelt==1.0.0 in /usr/local/lib/python3.12/site-packages (from pybmr>=0.7.8) (1.0.0)
Requirement already satisfied: requests==2.31.0 in /usr/local/lib/python3.12/site-packages (from pybmr>=0.7.8) (2.31.0)
Requirement already satisfied: urllib3==1.26.18 in /usr/local/lib/python3.12/site-packages (from pybmr>=0.7.8) (1.26.18)
INFO: pip is looking at multiple versions of pybmr to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install pybmr==0.7.8 because these package versions have conflicting dependencies.

The conflict is caused by:
    pybmr 0.7.8 depends on charset-normalizer==2.0.9
    The user requested (constraint) charset-normalizer==3.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

**Comment by zelial** [comment]
Regarding shutters: Me too! Coding support into pybmr has been long on my todolist. Any chance you guys would pick the work up? Even filing a RFE here would help ;)

**Comment by Rotif** [comment]
Hi,
I´m not able to install pybmr 
![Snímek obrazovky 2024-02-29 223629](https://github.com/slesinger/HomeAssistant-BMR/assets/114533831/75c969ca-77c0-4275-88e3-a56eaa6d54c3)

**Comment by vsechnozabrany** [comment]
@zelial @Dehumanizer77 sry for OT but you guys having roller shutters from BMR integrated into HA?

**Comment by Dehumanizer77** [comment]
@Rotif what type of installation you have? I have it on a VM with HassOS, but other installations might work differently. Try only pip install --no-deps pybmr==0.7.8

**Comment by Dehumanizer77** [comment]
@vsechnozabrany I do, but I had to create my own script running on a separate webserver I have at home, which interacts with the web interface of bmr and I'm only sending commands to that script from HA.
This is only because I'm not familiar with programming integrations in HA, otherwise I would do it directly as an integration, or change this existing BMR integration and add the functionality there, as this integration does it exactly the same way, it logs into bmr web interface and changes values there. If I will have time in a distant future, I might try to learn programming HA integrations :-)

Other way would be to do it via Modbus completely, but that would mean creating a completely new integration.

**Comment by vsechnozabrany** [comment]
@Dehumanizer77 alright, I am not that experienced though, I ll live without them in HA I guess
BTW about the Modbus, to activate you ll need access to service menu from manufacturer + they told me enabling Modbus gonna disable the "normal" run and e.g. heating will stop using defined schedule, instead it ll take these from Modbus as well

**Comment by Rotif** [comment]
@Dehumanizer77
My HA is running on Raspberry Pi
@vsechnozabrany 
itś true, modbuds take over komplet control

**Comment by vsechnozabrany** [comment]
@Rotif I guess you have the same setup as I. RPi with Hassio - then you need to install BMR through HACS integration by adding custom repository.

**Comment by zelial** [comment]
Shutters/blinds: I've created separate issues for the support of these. Lets move the discussion there.

https://github.com/slesinger/HomeAssistant-BMR/issues/10
https://github.com/slesinger/pybmr/issues/15

**Comment by Rotif** [comment]
The same result:
![Snímek obrazovky 2024-03-04 203027](https://github.com/slesinger/HomeAssistant-BMR/assets/114533831/bebe3fa6-4f5c-4e15-97b9-f0b1b982f561)

**Comment by slesinger** [comment]
I have release version 0.7.9 that installs well in HA latest container. (0.7.8 did not install). Can you please test it?

**Comment by Dehumanizer77** [comment]
Perfect, seems it works. I just had a HA Core update to install and after installation and HA restart BMR still works without installing pybmr manually.

**Comment by slesinger** [comment]
Thanks for the confirmation.
