### ISSUE TITLE
Update version 879edbc

### ISSUE THREAD

**Issue by Rotif** [slesinger/HomeAssistant-BMR#8]
Hi,
i have version 717c935 and now i can see in HACS upgrade, but when i try do it, upgrade begin but without end.
I've tryied delete custom_components/bmr and manualy copied integration but result is the same.
How should i do upgrade?
Thank you
Libor

**Comment by tobilos81** [comment]
Hi @Rotif , @slesinger , yesterday I found that there is unresolved conflict in [https://github.com/slesinger/HomeAssistant-BMR/blob/master/custom_components/bmr/manifest.json](https://github.com/slesinger/HomeAssistant-BMR/blob/master/custom_components/bmr/manifest.json). That is why the upgrade/Download does not work.

**Comment by Rotif** [comment]
Hi,
will you fix it? If not, how do I cancel the upgrade request from HACS?
Thanx

**Comment by Dehumanizer77** [comment]
@slesinger I have created a pull request to fix the issue: https://github.com/slesinger/HomeAssistant-BMR/pull/9

**Comment by Rotif** [comment]
@Dehumanizer77
i have copied your manifest.json in BMR folder, but nothing happend.
Thanx

**Comment by Dehumanizer77** [comment]
@Rotif you have either to use my forked version of the repository at https://github.com/Dehumanizer77/HomeAssistant-BMR or wait until @slesinger will merge the pull request.

**Comment by slesinger** [comment]
Merge. I am very sorry for delay.
